// Generated by gencpp from file line_tracing/cmd_stamped.msg
// DO NOT EDIT!


#ifndef LINE_TRACING_MESSAGE_CMD_STAMPED_H
#define LINE_TRACING_MESSAGE_CMD_STAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace line_tracing
{
template <class ContainerAllocator>
struct cmd_stamped_
{
  typedef cmd_stamped_<ContainerAllocator> Type;

  cmd_stamped_()
    : header()
    , cmd_num(0)  {
    }
  cmd_stamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cmd_num(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _cmd_num_type;
  _cmd_num_type cmd_num;





  typedef boost::shared_ptr< ::line_tracing::cmd_stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::line_tracing::cmd_stamped_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_stamped_

typedef ::line_tracing::cmd_stamped_<std::allocator<void> > cmd_stamped;

typedef boost::shared_ptr< ::line_tracing::cmd_stamped > cmd_stampedPtr;
typedef boost::shared_ptr< ::line_tracing::cmd_stamped const> cmd_stampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::line_tracing::cmd_stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::line_tracing::cmd_stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace line_tracing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'line_tracing': ['/home/turtlebot/catkin_ws/src/line_tracing/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::line_tracing::cmd_stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_tracing::cmd_stamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_tracing::cmd_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_tracing::cmd_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_tracing::cmd_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_tracing::cmd_stamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::line_tracing::cmd_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32c7c280a81068f50612cb2e16ef6493";
  }

  static const char* value(const ::line_tracing::cmd_stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32c7c280a81068f5ULL;
  static const uint64_t static_value2 = 0x0612cb2e16ef6493ULL;
};

template<class ContainerAllocator>
struct DataType< ::line_tracing::cmd_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "line_tracing/cmd_stamped";
  }

  static const char* value(const ::line_tracing::cmd_stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::line_tracing::cmd_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
int8 cmd_num\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::line_tracing::cmd_stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::line_tracing::cmd_stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cmd_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd_stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::line_tracing::cmd_stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::line_tracing::cmd_stamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cmd_num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cmd_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINE_TRACING_MESSAGE_CMD_STAMPED_H
