// Generated by gencpp from file localize/slam_stamped.msg
// DO NOT EDIT!


#ifndef LOCALIZE_MESSAGE_SLAM_STAMPED_H
#define LOCALIZE_MESSAGE_SLAM_STAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace localize
{
template <class ContainerAllocator>
struct slam_stamped_
{
  typedef slam_stamped_<ContainerAllocator> Type;

  slam_stamped_()
    : header()
    , x(0.0)
    , y(0.0)
    , th(0.0)  {
    }
  slam_stamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , th(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _th_type;
  _th_type th;





  typedef boost::shared_ptr< ::localize::slam_stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localize::slam_stamped_<ContainerAllocator> const> ConstPtr;

}; // struct slam_stamped_

typedef ::localize::slam_stamped_<std::allocator<void> > slam_stamped;

typedef boost::shared_ptr< ::localize::slam_stamped > slam_stampedPtr;
typedef boost::shared_ptr< ::localize::slam_stamped const> slam_stampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localize::slam_stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localize::slam_stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace localize

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'localize': ['/home/turtlebot/catkin_ws/src/localize/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::localize::slam_stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localize::slam_stamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localize::slam_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localize::slam_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localize::slam_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localize::slam_stamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localize::slam_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "070c2e7008392a0eaca5e92358e0f13f";
  }

  static const char* value(const ::localize::slam_stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x070c2e7008392a0eULL;
  static const uint64_t static_value2 = 0xaca5e92358e0f13fULL;
};

template<class ContainerAllocator>
struct DataType< ::localize::slam_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localize/slam_stamped";
  }

  static const char* value(const ::localize::slam_stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localize::slam_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
float32 x\n\
float32 y\n\
float32 th\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::localize::slam_stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localize::slam_stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.th);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct slam_stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localize::slam_stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localize::slam_stamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "th: ";
    Printer<float>::stream(s, indent + "  ", v.th);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZE_MESSAGE_SLAM_STAMPED_H
